development:
  adapter: postgresql
  encoding: utf8
  database: dashtag_solo_development
  template: template0
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: dashtag_solo_test
  template: template0
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: dashtag_solo_production
  template: template0
  pool: 5